### ISSUE TITLE
bug fixes

### ISSUE THREAD

**Issue by nirazanbasnet** [open-contracting/covid-19-procurement-explorer-public#290]
- [ ] #7 Add prooflink which leads to the country public procurement portal.
- [ ] #55 Add topic & language section in resource detail page
- [ ] #59 country profile - partners section link to add
- [ ] #10 remove product timeline on the top of each buyer profile
